// <auto-generated />
using System;
using Labb4_MVCRazor.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb4_MVCRazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb4_MVCRazor.Models.ActiveBorrows", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ActiveBorrows");
                });

            modelBuilder.Entity("Labb4_MVCRazor.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookCategory")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Published")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Ajvide Lindqvist",
                            BookCategory = 1,
                            Description = "If fiction’s taught us anything in recent years, it’s that the vampire genre can be a tired—and ironically toothless—one. But Swedish writer John Ajvide Lindqvist breathed new life into the eternally overdone tale with his debut novel, Let the Right One In, which tells the story of a bullied grade-school student named Oskar and his new friend and neighbor, Eli.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/bf/Lettherightoneinswedishbookcover.jpg",
                            Published = 2004,
                            SerialNumber = "x11111",
                            Title = "Let The Right One in"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Stephen King",
                            BookCategory = 1,
                            Description = "If fiction’s taught us anything in recent years, it’s that the vampire genre can be a tired—and ironically toothless—one. But Swedish writer John Ajvide Lindqvist breathed new life into the eternally overdone tale with his debut novel, Let the Right One In, which tells the story of a bullied grade-school student named Oskar and his new friend and neighbor, Eli.",
                            ImageUrl = "http://cdn.pastemagazine.com/www/articles/ItKing.jpg",
                            Published = 1986,
                            SerialNumber = "x11112",
                            Title = "It"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Shirley Jackson",
                            BookCategory = 1,
                            Description = "No live organism can continue for long to exist sanely under conditions of absolute reality; even larks and katydids are supposed, by some, to dream. Hill House, not sane, stood by itself against the hills, holding darkness within; it had stood so for eighty years and might stand for eighty more.",
                            ImageUrl = "http://cdn.pastemagazine.com/www/articles/HauntingofHillHouseJackson.jpg",
                            Published = 1986,
                            SerialNumber = "x11113",
                            Title = "The Haunting of Hill House"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Ian Flemming",
                            BookCategory = 2,
                            Description = "Casino Royale is the first novel by the British author Ian Fleming. Published in 1953, it is the first James Bond book, and it paved the way for a further eleven novels and two short story collections by Fleming, followed by numerous continuation Bond novels by other authors. ",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a9/CasinoRoyaleCover.jpg",
                            Published = 1953,
                            SerialNumber = "x11114",
                            Title = "Casino Royale"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Luke Jennings",
                            BookCategory = 2,
                            Description = "Killing Eve: Die for Me is a 2020 thriller novel by British author Luke Jennings. It is the third and final installment in the Killing Eve series, following Codename Villanelle (2017) and Killing Eve: No Tomorrow (2018).[1] The novel was published in the United Kingdom by John Murray as an e-book on 9 April 2020,[2] followed by hardcover and paperback versions on 11 June and 12 November 2020, respectively.[3][4] The novels are the basis of the BBC America television series Killing Eve (2018–2022).",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/91/Killing_Eve_Die_for_Me_book_cover.png",
                            Published = 2020,
                            SerialNumber = "x11115",
                            Title = "Killing Eve: Die for Me"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Ernest Cline",
                            BookCategory = 2,
                            Description = "Ready Player One is a 2011 science fiction novel, and the debut novel of American author Ernest Cline. The story, set in a dystopia in 2045, follows protagonist Wade Watts on his search for an Easter egg in a worldwide virtual reality game, the discovery of which would lead him to inherit the game creator's fortune. Cline sold the rights to publish the novel in June 2010, in a bidding war to the Crown Publishing Group (a division of Random House).[1] The book was published on August 16, 2011.[2] An audiobook was released the same day; it was narrated by Wil Wheaton, who was mentioned briefly in one of the chapters.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/Ready_Player_One_cover.jpg",
                            Published = 2011,
                            SerialNumber = "x11116",
                            Title = "Ready Player One"
                        },
                        new
                        {
                            Id = 7,
                            Author = "C.S. Lewis",
                            BookCategory = 3,
                            Description = "The Lion, the Witch and the Wardrobe is a fantasy novel for children by C. S. Lewis, published by Geoffrey Bles in 1950. It is the first published and best known of seven novels in The Chronicles of Narnia (1950–1956). Among all the author's books, it is also the most widely held in libraries.[2] Although it was originally the first of The Chronicles of Narnia, it is volume two in recent editions that are sequenced by the stories' chronology. Like the other Chronicles, it was illustrated by Pauline Baynes, and her work has been retained in many later editions.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/86/TheLionWitchWardrobe%281stEd%29.jpg",
                            Published = 1950,
                            SerialNumber = "x11117",
                            Title = "The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Ken Liu",
                            BookCategory = 3,
                            Description = "Complex, ambitious, and drop-dead gorgeous, the first book in Ken Liu’s Dandelion Dynasty series is an intricately plotted fantasy epic. Former enemies become allies to overturn an ancient empire, rendered in beautiful prose that showcases Liu’s “silkpunk” style—East Asian-inspired cultures alongside fantastical technology like airships and battle kites.",
                            ImageUrl = "https://static.wikia.nocookie.net/the-dandelion-dynasty/images/8/8f/18952341.jpg/revision/latest/scale-to-width-down/314?cb=20170130212114",
                            Published = 1978,
                            SerialNumber = "x11118",
                            Title = "The Grace of Kings"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Scott Hawkins",
                            BookCategory = 3,
                            Description = "Carolyn and her eleven siblings live together in the house of their father, a seemingly immortal man whose library grants them special powers. To say anything else would spoil this riveting, one-of-a-kind novel full of surprises and paced like a thriller.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/94/The_Library_At_Mount_Char_book_cover.jpg",
                            Published = 2015,
                            SerialNumber = "x11119",
                            Title = "The Library at Mount Char"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Sally Roney",
                            BookCategory = 4,
                            Description = "This quiet love story centers around Alice, Felix, Eileen and Simon — four people trying to find their way in the world. Romantic entanglement ensues (this is a Rooney novel, after all) and you'll find your own allegiances shifting and changing as you read.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/31/Beautiful_World%2C_Where_Are_You_-_1st_UK_edition_cover.jpg",
                            Published = 2021,
                            SerialNumber = "x11120",
                            Title = "Beautiful World, Where Are You"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Sally Roney",
                            BookCategory = 4,
                            Description = "Twenty years ago, Eva and Shane fell in love over a whirlwind of a week. When they happen to reconnect in Brooklyn, Eva (now an erotica writer) and Shane (now a bestselling author) have a chance at closure, or rekindling the spark that brought them together in the first place. It's sexy, sultry and deliciously steamy.",
                            ImageUrl = "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1621846249l/55648820._SY475_.jpg",
                            Published = 2021,
                            SerialNumber = "x11121",
                            Title = "Seven Days in June"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Andre Aciman",
                            BookCategory = 4,
                            Description = "This quiet love story centers around Alice, Felix, Eileen and Simon — four people trying to find their way in the world. Romantic entanglement ensues (this is a Rooney novel, after all) and you'll find your own allegiances shifting and changing as you read.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c9/CallMeByYourName2017.png",
                            Published = 2007,
                            SerialNumber = "x11122",
                            Title = "Call Me by Your Name"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Walter Isaacson",
                            BookCategory = 5,
                            Description = "The man, the myth, the legend: Steve Jobs, co-founder and CEO of Apple, is properly immortalized in Isaacson’s masterful biography. It divulges the details of Jobs’ little-known childhood and tracks his fateful path from garage engineer to leader of one of the largest tech companies in the world",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e4/Steve_Jobs_by_Walter_Isaacson.jpg",
                            Published = 2011,
                            SerialNumber = "x11123",
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Evelyn C. White",
                            BookCategory = 5,
                            Description = "Alice Walker has given us some of the most celebrated and beloved books, including The Color Purple, which made her the first Black woman to win a Pulitzer Prize. In this comprehensive biography, Evelyn C. White conducts extensive research and numerous interviews and draws connections between Walker’s early life events, societal ills, and the brilliant writer that Walker would become. ",
                            ImageUrl = "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348816682l/60936.jpg",
                            Published = 2004,
                            SerialNumber = "x11124",
                            Title = "Alice Walker: A Life"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Sally Bedell Smith",
                            BookCategory = 5,
                            Description = "If you can’t get enough of The Crown on Netflix, this biography will be your cup of tea. This is author Sally Bedell Smith’s third biography of a member of the royal family, and her expertise in making connections and presenting research shines.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2d/Queen_Elizabeth_the_Queen_Mother_portrait.jpg",
                            Published = 2012,
                            SerialNumber = "x11125",
                            Title = "Elizabeth the Queen: The Life of a Modern Monarch"
                        });
                });

            modelBuilder.Entity("Labb4_MVCRazor.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Phone_Number");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Lyckogatan 23",
                            Email = "oliver@rodin.com",
                            Name = "Oliver Rodin",
                            PhoneNumber = "070-3425467"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bergsvägen 32",
                            Email = "anna@andersson.com",
                            Name = "Anna Andersson",
                            PhoneNumber = "070-0985467"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Apparatgatan 1",
                            Email = "fredrik@fredriksson.com",
                            Name = "Fredrik Fredriksson",
                            PhoneNumber = "070-3400067"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alftavägen 20",
                            Email = "annika@lantz.com",
                            Name = "Annika Lantz",
                            PhoneNumber = "070-3420107"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hjulgatan 45",
                            Email = "jessica@andersson.com",
                            Name = "Jessica Andersson",
                            PhoneNumber = "070-3420000"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Skogsgatan 100",
                            Email = "magnus@dixon.com",
                            Name = "Magnus Dixon",
                            PhoneNumber = "070-3421111"
                        });
                });

            modelBuilder.Entity("Labb4_MVCRazor.Models.ReturnedBorrows", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ReturnedBorrows");
                });

            modelBuilder.Entity("Labb4_MVCRazor.Models.ActiveBorrows", b =>
                {
                    b.HasOne("Labb4_MVCRazor.Models.Book", "Book")
                        .WithMany("ActiveBorrows")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb4_MVCRazor.Models.Customer", "Customer")
                        .WithMany("ActiveBorrows")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb4_MVCRazor.Models.ReturnedBorrows", b =>
                {
                    b.HasOne("Labb4_MVCRazor.Models.Book", "Book")
                        .WithMany("ReturnedBorrows")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb4_MVCRazor.Models.Customer", "Customer")
                        .WithMany("ReturnedBorrows")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb4_MVCRazor.Models.Book", b =>
                {
                    b.Navigation("ActiveBorrows");

                    b.Navigation("ReturnedBorrows");
                });

            modelBuilder.Entity("Labb4_MVCRazor.Models.Customer", b =>
                {
                    b.Navigation("ActiveBorrows");

                    b.Navigation("ReturnedBorrows");
                });
#pragma warning restore 612, 618
        }
    }
}
